## 获取矩阵索引

In [1]:
import torch
num_nodes = 4
ones = torch.ones(num_nodes, num_nodes)
eye = torch.eye(num_nodes, num_nodes)

In [6]:
ones.triu() - eye

tensor([[0., 1., 1., 1.],
        [0., 0., 1., 1.],
        [0., 0., 0., 1.],
        [0., 0., 0., 0.]])

In [11]:
(ones.triu() - eye).nonzero().t()

tensor([[0, 0, 0, 1, 1, 2],
        [1, 2, 3, 2, 3, 3]])

In [10]:
(ones.triu() - eye).nonzero().t()[0] * num_nodes + (ones.triu() - eye).nonzero().t()[1]

tensor([ 1,  2,  3,  6,  7, 11])

In [12]:
def get_triu_indices(num_nodes):
    """Linear triu (upper triangular) indices."""
    ones = torch.ones(num_nodes, num_nodes)
    eye = torch.eye(num_nodes, num_nodes)
    triu_indices = (ones.triu() - eye).nonzero().t()
    triu_indices = triu_indices[0] * num_nodes + triu_indices[1]
    return triu_indices


def get_tril_indices(num_nodes):
    """Linear tril (lower triangular) indices."""
    ones = torch.ones(num_nodes, num_nodes)
    eye = torch.eye(num_nodes, num_nodes)
    tril_indices = (ones.tril() - eye).nonzero().t()
    tril_indices = tril_indices[0] * num_nodes + tril_indices[1]
    return tril_indices


def get_offdiag_indices(num_nodes):
    """Linear off-diagonal indices."""
    ones = torch.ones(num_nodes, num_nodes)
    eye = torch.eye(num_nodes, num_nodes)
    offdiag_indices = (ones - eye).nonzero().t()
    offdiag_indices = offdiag_indices[0] * num_nodes + offdiag_indices[1]
    return offdiag_indices

In [13]:
triu_indices = get_triu_indices(5)
tril_indices = get_tril_indices(5)
offdiag_indices = get_offdiag_indices(5)
print(triu_indices)
print(tril_indices)
print(offdiag_indices)

tensor([ 1,  2,  3,  4,  7,  8,  9, 13, 14, 19])
tensor([ 5, 10, 11, 15, 16, 17, 20, 21, 22, 23])
tensor([ 1,  2,  3,  4,  5,  7,  8,  9, 10, 11, 13, 14, 15, 16, 17, 19, 20, 21,
        22, 23])


In [20]:
num_nodes = 5
triu_idx = torch.zeros(num_nodes * num_nodes)
triu_idx[get_triu_indices(num_nodes)] = 1.
triu_idx = triu_idx[get_offdiag_indices(num_nodes)]
print(triu_idx)

tensor([1., 1., 1., 1., 0., 1., 1., 1., 0., 0., 1., 1., 0., 0., 0., 1., 0., 0.,
        0., 0.])


In [21]:
triu_idx.nonzero()

tensor([[ 0],
        [ 1],
        [ 2],
        [ 3],
        [ 5],
        [ 6],
        [ 7],
        [10],
        [11],
        [15]])